_target_: model.jepa.JEPA

encoder:
  _target_: model.module.MobileNetEncoder
  embed_dim: ${embed_dim}
  pretrained: false  # Set to false to avoid SSL cert issues when downloading pretrained weights

predictor:
  _target_: model.module.ARPredictor
  num_frames: ${history_size}
  input_dim: ${embed_dim}
  hidden_dim: ${embed_dim}
  output_dim: ${embed_dim}
  depth: 6
  heads: 16
  mlp_dim: 2048
  dim_head: 64
  dropout: 0.1
  emb_dropout: 0.0

action_encoder:
  _target_: model.module.Embedder
  input_dim: ???
  emb_dim: ${embed_dim}

projector:
  _target_: model.module.MLP
  input_dim: ${embed_dim}
  output_dim: ${embed_dim}
  hidden_dim: 2048
  norm_fn:
    _target_: torch.nn.BatchNorm1d
    _partial_: true

pred_proj:
  _target_: model.module.MLP
  input_dim: ${embed_dim}
  output_dim: ${embed_dim}
  hidden_dim: 2048
  norm_fn:
    _target_: torch.nn.BatchNorm1d
    _partial_: true
